from fastapi import APIRouter
from app.api.v1.endpoints import (
    auth, usuarios, estibas, ubicaciones, proveedores,
    vehiculos, manifiestos, movimientos, dashboard, alertas, danos, tarifax, mantenimiento, consultas, roles, fletes, flota, locative, wms, hcm, tms, dms, qms, grc, lms, crm, eam, mes, aps, erp, scan_sessions
)

api_router = APIRouter()

api_router.include_router(erp.router)
api_router.include_router(auth.router)
api_router.include_router(roles.router)
api_router.include_router(usuarios.router)
api_router.include_router(estibas.router)
api_router.include_router(ubicaciones.router)
api_router.include_router(proveedores.router)
api_router.include_router(vehiculos.router)
api_router.include_router(manifiestos.router)
api_router.include_router(movimientos.router)
api_router.include_router(dashboard.router)
api_router.include_router(alertas.router)
api_router.include_router(danos.router)
api_router.include_router(tarifax.router)
api_router.include_router(mantenimiento.router)
api_router.include_router(consultas.router)
api_router.include_router(fletes.router)
api_router.include_router(flota.router)
api_router.include_router(locative.router)
api_router.include_router(wms.router)
api_router.include_router(hcm.router)
api_router.include_router(tms.router)
api_router.include_router(dms.router)
api_router.include_router(qms.router)
api_router.include_router(grc.router)
api_router.include_router(lms.router)
api_router.include_router(crm.router)
api_router.include_router(eam.router)
api_router.include_router(mes.router)
api_router.include_router(aps.router)
api_router.include_router(scan_sessions.router)
